name: Monthly FR Contribution PR

on:
  schedule:
    - cron: '0 0 27-30 * *'
  workflow_dispatch:

jobs:
  prepare-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Orsoniks/scavgame-locale.git
          git fetch upstream

      - name: Check if tomorrow is last day of month
        id: datecheck
        run: |
          if [ "$(date -d '+2 day' +%d)" -eq "01" ]; then
            echo "lastday=true" >> "$GITHUB_OUTPUT"
          else
            echo "lastday=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit if not penultimate day
        if: ${{ steps.datecheck.outputs.lastday == 'false' && github.event_name != 'workflow_dispatch' }}
        run: |
          echo "Not the penultimate day of the month. Exiting."
          exit 0

      - name: Sync fork main with upstream
        run: |
          git checkout main
          git pull --ff-only upstream main
          git push origin main

      - name: Update FR.json (and possibly README.md)
        id: update
        run: |
          changed_fr=false
          changed_readme=false

          git checkout upstream/main -- FR.json
          if ! git diff --quiet -- FR.json; then
            changed_fr=true
          fi

          git checkout upstream/main -- README.md
          if ! git diff --quiet -- README.md; then
            changed_readme=true
          else
            git checkout -- README.md
          fi

          if [ "$changed_fr" = "false" ] && [ "$changed_readme" = "false" ]; then
            echo "No changes detected, exiting."
            exit 0
          fi

          echo "changed_fr=$changed_fr" >> "$GITHUB_OUTPUT"
          echo "changed_readme=$changed_readme" >> "$GITHUB_OUTPUT"

          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add FR.json README.md || true

          commit_msg="Update FR.json"
          if [ "$changed_readme" = "true" ]; then
            commit_msg="$commit_msg and README.md"
          fi

          git commit -m "$commit_msg"

      - name: Push fork update branch
        run: |
          git checkout -B fr-update
          git remote set-url origin https://x-access-token:${MONTHLY_PR_TOKEN}@github.com/${{ github.repository }}.git
          git push -u origin fr-update --force
        env:
          MONTHLY_PR_TOKEN: ${{ secrets.MONTHLY_PR_TOKEN }}

      - name: Create or update Pull Request to upstream
        env:
          GH_TOKEN: ${{ secrets.MONTHLY_PR_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list \
            --repo Orsoniks/scavgame-locale \
            --head "${{ github.repository_owner }}:fr-update" \
            --json number -q '.[0].number')

          body="This PR contains the updated \`FR.json\`"
          if [ "${{ steps.update.outputs.changed_readme }}" == "true" ]; then
            body="$body and \`README.md\`"
          fi
          body="$body\n\nLast updated automatically on $(date +'%Y-%m-%d')."

          if [ -z "$PR_NUMBER" ]; then
            gh pr create \
              --repo Orsoniks/scavgame-locale \
              --head "${{ github.repository_owner }}:fr-update" \
              --base main \
              --title "FR.json monthly update" \
              --body "$body"
          else
            gh pr edit "$PR_NUMBER" \
              --repo Orsoniks/scavgame-locale \
              --title "FR.json monthly update" \
              --body "$body"
          fi
