name: Monthly FR Contribution PR

on:
  schedule:
    # Run at midnight UTC on days 27–30; we'll filter inside
    - cron: '0 0 27-30 * *'
  workflow_dispatch:

jobs:
  prepare-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Orsoniks/scavgame-locale.git
          git fetch upstream

      - name: Check if tomorrow is last day of month
        id: datecheck
        run: |
          if [ "$(date -d '+2 day' +%d)" -eq "01" ]; then
            echo "lastday=true" >> "$GITHUB_OUTPUT"
          else
            echo "lastday=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit if not penultimate day
        if: steps.datecheck.outputs.lastday == 'false' && github.event_name != 'workflow_dispatch'
        run: |
          echo "Not the penultimate day of the month. Exiting."
          exit 0

      - name: Sync fork main with upstream
        run: |
          git checkout main
          git pull --ff-only upstream main
          git push origin main

      - name: Update FR.json (and possibly README.md)
        id: update
        run: |
          # Track file changes
          changed_fr=false
          changed_readme=false

          git checkout upstream/main -- FR.json
          if ! git diff --quiet -- FR.json; then
            changed_fr=true
          fi

          git checkout upstream/main -- README.md
          if ! git diff --quiet -- README.md; then
            changed_readme=true
          else
            git checkout -- README.md # discard if unchanged
          fi

          # Exit if no changes
          if [ "$changed_fr" = "false" ] && [ "$changed_readme" = "false" ]; then
            echo "No changes detected, exiting."
            exit 0
          fi

          # Set outputs
          echo "changed_fr=$changed_fr" >> "$GITHUB_OUTPUT"
          echo "changed_readme=$changed_readme" >> "$GITHUB_OUTPUT"

          # Commit
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add FR.json README.md || true

          commit_msg="Update FR.json"
          if [ "$changed_readme" = "true" ]; then
            commit_msg="$commit_msg and README.md"
          fi

          git commit -m "$commit_msg"

      - name: Push fork main
        run: |
          git remote set-url origin https://x-access-token:${MONTHLY_PR_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
        env:
          MONTHLY_PR_TOKEN: ${{ secrets.MONTHLY_PR_TOKEN }}

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MONTHLY_PR_TOKEN }}
          commit-message: "Update FR.json"
          title: "FR.json monthly update"
          body: |
            This PR contains the updated `FR.json`$([[ "${{ steps.update.outputs.changed_readme }}" == "true" ]] && echo " and `README.md`").

            Last updated automatically on $(date +'%Y-%m-%d').
          base: main
          branch: main
          repository: Orsoniks/scavgame-locale
          delete-branch: false
